
puts "\033\[33m################################################################"
puts         "#################  Define  CPF   variables #####################"
puts 	     "################################################################"
puts "\033\[36mAll the power domain related definitions are usually stored in a \033\[35mcommon power format (\033\[32mcpf\033\[35m)"
puts "\033\[36mThis script is executed from the main synthesis script by the command \033\[35msource script/prepare_CPF_input.tcl\033\[0m"
puts "\033\[36mIt helps you to prepare your own CPF description for the following synthesis steps.                 "
puts "\033\[36m                                                                \033\[0m"
puts "\033\[36mFirst, you need to define the delay and power behaviour of the standard and memory cells in the     "
puts "\033\[36mgiven technology.                                                                                  "
puts "\033\[36mFor analysis and mitigation of all possible failures, several conditions and process variation corners need to be included."
puts "\033\[36mHence multiple analysis views are created and multiple lib models of same cell must be included."
puts "\033\[36mIn our lab, only one corners are considered: the slowest to prevent setup violations."
puts "\033\[36mYou will have two power domains for voltages of \033\[35m1.2V and  1.0V"
puts "\033\[36mHence, you need to include \033\[33mfour library sets for every power domain."
puts "\033\[36m\t* The variable \033\[35mslow_\033\[32mHV\033\[35m_libs \033\[36mdefines the libraries for \033\[32mH\033\[36migher \033\[32mV\033\[36moltage domain"
puts "\t* The variable slow_LV_libs defines the libraties for Lower  Voltage domain"
puts "\t* Both variables are lists"
puts "\t\t* In tcl, the lists are strings with words inside separated by space"
puts "\t\t* list example: \033\[35mset list1 \"a b c d\""
puts "\t\t\033\[36m*adding to the list: \033\[35mlappend list1 \"e f\""
puts "\t\033\[36m*The libraries needed for every domain through the synthesis:"
puts "\t\ta. library for timing/power behaviour of regular cells under given voltage"
puts "\t\tb. library for timing/power behaviour of memory cells under given voltage"
puts "\t\tc. library for timing/power behaviour of level shifter from this to all other power domains"
puts "\033\[32mTIP   : \033\[36mGPDK45 variable hold the location of the technology folder with all libraries necessary"
puts "\033\[34mHINT 1:\033\[36m Look for worst case conditions, because the product of the synthesis should worst under worst possible conditions"
puts "\033\[34mHINT 2: \033\[36mWhile picking the worst case behaviour libraries remember: \"hold\" violations are not considered yet\033\[0m"
puts "\033\[34mHINT 3: \033\[36mThe lib files are in \$GPDK045/gsclib045/timing/.\033\[0m"
puts "\033\[33mDefine the library sets for the timing analysis"
puts "\033\[36mYou will be guided here command by command.                     \033\[0m"
puts "\033\[33m-----> Set the timing library path for slowest basic regular(basic) for voltage of 1.2V in variable \033\[35mslow_HV_a\033\[0m"
suspend
puts "\033\[33m-----> Set the timing library path for slowest level shifter cells from voltage 1.2V to 1.0V (1.0V is EXTernal voltage) in \033\[35mslow_HV_b \033\[0m"
suspend
puts "\033\[33m-----> Set the timing library path for slowest memory cells for voltage of 1.2V in \033\[35mslow_HV_c\033\[0m"
puts "\033\[34mHINT:\033\[36m the lib files of the memory are in ./lib/\033\[0m"
suspend
puts "\033\[33m-----> Bundle all the variables in a list under name \033\[35mslow_HV_libs\033\[0m"
puts "-----> \033\[32mset slow_HV_lib \"\$slow_HV_a \$slow_HV_b \$slow_HV_c\"\033\[0m"
suspend
puts "\n\033\[33m------>***<--------\n"
puts "\033\[33m-----> Set the timing libarary path for the slowest basic cells for voltage of 1.0V in variable slow_LV_a\033\[0m"
suspend
puts "\033\[33m ----> Set the timing library path for the slowest level shifter cells from voltage 1.0V to 1.2V (1.2V is EXTernal voltage) in variable \033\[35mslow_LV_b\033\[0m"
suspend
puts "\033\[33m-----> Set the timing library path for the slowest memory cells for voltage of 1.0V in variable slow_LV_c\033\[0m"
puts "\033\[34mHint:\033\[36m The script is designed to be generic, but if you know    \033\[0m"
puts "\033\[36m     you will have no  memory at Low Voltage you may as well skip this  \033\[0m"
puts "\033\[36m     step. Same counts for every of the following steps.                 \033\[0m"
puts "\033\[36m                                                                        \033\[0m"
suspend
puts "\033\[33m-----> Bundle all the variables in a list under name \033\[35mslow_LV_lib\033\[0m"
suspend
# Commented out the inclusion of fastest libraries because they are not used in frontend (DTT)
#puts "\033\[33m-----> Set the library for the fastest basic cells for voltage of 1.2V in variable \033\[35mfast_HV_a\033\[0m"
#suspend
#puts "\033\[33m-----> Set the library for the fastest level shifter cells from voltage 1.2V to 1.0V (1.0V is EXTernal voltage) in \033\[35mfast_HV_b \033\[0m"
#suspend
#puts "\033\[33m-----> Set the library for the fastest memory cells for voltage of 1.2V in \033\[35mfast_HV_c\033\[0m"
#suspend
#puts "\033\[33m-----> Bundle all the libraries in a list under name fast_HV_lib"
#puts "-----> \033\[32mset fast_HV_lib \"\$fast_HV_a \$fast_HV_b \$fast_HV_c\"\033\[0m"
#suspend
#puts "\n\033\[33m------>***<--------\n"
#puts "\033\[33m-----> Set the libarary for fastest basic cells for voltage of 1.0V in variable \033\[35mfast_LV_a\033\[0m"
#suspend
#puts "\033\[33m ----> Set the library for fastest level shifter cells from voltage 1.0V to 1.2V (1.2V is EXTernal voltage) in variable \033\[35mfast_LV_b\033\[0m"
#suspend
#puts "\033\[33m-----> Set the library for fastest memory cells for voltage of 1.0V in variable fast_LV_c\033\[0m"
#suspend
#puts "\033\[33m-----> Bundle all the libraries in a list under name \033\[35mfast_LV_lib\033\[0m"
#suspend
puts "\033\[36m Now you defined four lists"
puts "\033\[36m Those tcl list variables are used in cpf file to define the library sets"
puts "\033\[36m You can open \033\[35mcpf/MIPS_tmpl.cpf \033\[36mand look how they are used.                      \033\[0m"
puts "\033\[36m The cpf command for this is \033\[35mdefine_libraty_set -name set_name -libraries lib_list.  \033\[0m"
puts "\033\[36m Later with script/prepare_CPF_file.tcl script a new MIPS.cpf file is created."
puts "\033\[36m Instead of lib_list you can find there the variables, you just defined     \033\[0m"
puts "\033\[36m Enter resume to continue                                                   \033\[0m"
suspend

puts "\033\[36m Now you should define the supply voltage net names for voltages of 1.0V and 1.2V     \033\[0m"
puts "\033\[36m The commands  for that in the MIPS.cpf file  are:             \033\[0m"
puts "\033\[36m         * create_power_nets -nets \033\[33m\$VDD1_name\033\[36m -voltage \033\[33m\$VDD1_voltage \033\[0m"
puts "\033\[36m         * create_power_nets -nets \033\[33m\$VDD2_name\033\[36m -voltage \033\[33m\$VDD2_voltage \033\[0m"
puts "\033\[36m         * create_ground_nets -nets VSS                         \033\[0m"
puts "\033\[36m                                                                \033\[0m"
puts "\033\[33m Define the variables \$VDD1_name, \$VDD1_voltage and \$VDD2_name, \$VDD2_voltage     \033\[0m"
puts "\033\[34m HINT: \033\[36m For first, make VDD1 to 1.0 (V) and VDD2 to 1.2 (V)           \033\[0m"
suspend
puts "\033\[36m Now define the power domains and associate them with the instances from the design.       \033\[0m"
puts "\033\[36m The CPF commands for this are:                                 \033\[0m"
puts "\033\[36m     create_power_domain -name \033\[33m\$PD1\033\[36m -default                   \033\[0m"
puts "\033\[36m     create_power_domain -name \033\[33m\$PD2\033\[36m -instances \033\[33m\$PD2_inst_list     \033\[0m"
puts "\033\[36m The option -default covers all instances                               \033\[0m"
puts "\033\[36m The following command then excludes some instances and assigns them to \$PD2.\033\[0m"
puts "\033\[36m The commands are already written you need to define PD1,PD2, PD2_inst_list. \033\[0m"
puts "\033\[36m         * PD1 and PD2 are just names define them as you wish.          \033\[0m"
puts "\033\[36m         * inst_list must be a tcl list of instance names               \033\[0m"
puts "\033\[36m         * interesting instance names from the top level of MMIPS sytem:      \033\[0m"
puts "\033\[36m           * imem sram cell for instruction memory                      \033\[0m"
puts "\033\[36m           * dmem sram cell for data memory                             \033\[0m"
puts "\033\[36m           * mMIPS the microcotroller                                   \033\[0m"
puts "\033\[36m           * u_aes the AES decryption core                              \033\[0m"
puts "\033\[36mREMARK:    Be aware that memories won't work with low voltage!          \033\[0m"
puts "\033\[33m Define PD1, PD2, PD2_inst_list.                                            \033\[0m"
suspend
puts "\033\[36m Now associate the defined domains with defined nets.                   \033\[0m"
puts "\033\[36m                                                                        \033\[0m"
puts "\033\[36m The CPF commands:                                                      \033\[0m"
puts "\033\[35m    update_power_domain -name \$PD1 -primary_power_net \$VDD1_name -primary_ground_net VSS \033\[0m"
puts "\033\[35m    update_power_domain -name \$PD2 -primary_power_net \$VDD2_name -primary_ground_net VSS \033\[0m"
puts "\033\[36m                                                                        \033\[0m"
puts "\033\[36m And for the net connection:                                            \033\[0m"
puts "\033\[35m    create_global_connection -domain \$PD1 -net \$VDD1_name -pins VDD    \033\[0m"
puts "\033\[35m    create_global_connection -domain \$PD2 -net \$VDD2_name -pins VDD    \033\[0m"
puts "\033\[35m    create_global_connection -domain \$PD1 -net \$VDD2_name -pins ExtVDD    \033\[0m"
puts "\033\[35m    create_global_connection -domain \$PD2 -net \$VDD1_name -pins ExtVDD    \033\[0m"
puts "\033\[36m                                                                        \033\[0m"
puts "\033\[36m                                                                        \033\[0m"
puts "\033\[36m                                                                        \033\[0m"
puts "\033\[36m When there are more than one power supply the tool needs a clear       \033\[0m"
puts "\033\[36m definition how to connect them to the cells.                           \033\[0m"
puts "\033\[36m The pins are taken from the cell definition of the corresponding lib   \033\[0m"
puts "\033\[36m files. ExtVDD are extra power pins of the level shifters, because      \033\[0m"
puts "\033\[36m generally they need to be connected to both power supplies. This step  \033\[0m"
puts "\033\[36m is already well defined and you do not need to do anything. The script \033\[0m"
puts "\033\[36m is stopped for the sake of clarity and function of those commands.   \033\[0m"
puts "\033\[36m  You do not need to do anything here. Proceed with resume command.         \033\[0m"
suspend
puts "\033\[36m The level shifter cells mentioned above are necessary for domain       \033\[0m"
puts "\033\[36m interconnection. Which level shifter cells are used, is defined with   \033\[0m"
puts "\033\[36m following commands:                                                    \033\[0m"
puts "\033\[36m      * define_level_shifter_cell defines the specific cell model       \033\[0m"
puts "\033\[36m      * create_level_shifter_rule defines the domain connection rule    \033\[0m"
puts "\033\[36m      * update_level_shifter_rules associates a cell with a rule        \033\[0m"
puts "\033\[36m An example definition is aready prepared in CPF file and should be     \033\[0m"
puts "\033\[36m functional. This step is merely for your information                   \033\[0m"
puts "\033\[36m                                                                        \033\[0m"
suspend
puts "\033\[36m Now create the operating conditions and associate them with power      \033\[0m"
puts "\033\[36m domains. This is the point where perviously defined library sets are   \033\[0m"
puts "\033\[36m connected with design over the corresponding power domains.            \033\[0m"
puts "\033\[36m                                                                        \033\[0m"
puts "\033\[36m The CPF commands:                                                      \033\[0m"
puts "\033\[35m  create_nominal_condition -name \$NC1 -voltage \$VDD1_voltage          \033\[0m"
puts "\033\[35m  create_nominal_condition -name \$NC2 -voltage \$VDD2_voltage          \033\[0m"
puts "\033\[36m                                                                        \033\[0m"
puts "\033\[35m  update_nominal_condition -name \$NC1 -library_set cadence45_wc_HV_lib \033\[0m"
puts "\033\[35m  update_nominal_condition -name \$NC2 -library_set cadence45_wc_LV_lib \033\[0m"
puts "\033\[36m                                                                        \033\[0m"
puts "\033\[36m  ! cadence45_wc_HV_lib, cadence45_wc_LV_lib library sets are defined  \033\[0m"
puts "\033\[36m    with previously mentioned define_library_set command.               \033\[0m"
puts "\033\[36m And finally, the connection of the condition and power domain is made          \033\[0m"
puts "\033\[36m by following command.                                                  \033\[0m"
puts "\033\[36m                                                                        \033\[0m"
puts "\033\[35m  create_power_mode -name PM1 -domain_conditions \"\$PD1@\$NC1 \$PD2@\$NC2\" -default \033\[0m"
puts "\033\[36m                                                                        \033\[0m"
puts "\033\[36m  The definition of power domains, nets and condition is    \033\[0m"
puts "\033\[36m  necessary to express different circuit operating conditions and their\033\[0m"
puts "\033\[36m  ans their proper analysis.                                            \033\[0m"
puts "\033\[36m The example command above defines domain \$PD1 to operate in \$NC1 etc.\033\[0m"
puts "\033\[33m  Define the names for NC1, NC2. Those are just labels, so everything is okay \033\[0m"
suspend


puts "\033\[32m  The CPF file definition is complete. Now your input is inserted        \033\[0m"
puts "\033\[32m  in MIPS.cpf file and this file is loaded by Genus synthesis tool  \033\[0m"
puts "\033\[32m  after you enter resume.                                               \033\[0m"
puts "\033\[32m  The script is checked by the tool and if you see any ERROR messages   \033\[0m"
puts "\033\[32m  in connection to timing libraries, power domains or CPF file, please  \033\[0m"
puts "\033\[36m  review your MIPS.cpf file for mistakes or eventually rerun this       \033\[0m"
puts "\033\[36m  script.                                                               \033\[0m"
puts "\033\[36m                                                                        \033\[0m"
puts "\033\[36m                                                                        \033\[0m"
puts "\033\[36m                                                                        \033\[0m"
puts "\033\[36m                                                                        \033\[0m"
puts "\033\[36m                                                                        \033\[0m"




